### ISSUE TITLE
users/auth 404 (Not Found) When I try to execute your login auth.

### ISSUE THREAD

**Issue by ericel** [aviabird/pinterest#13]
Any documentation for your app. I like the ngrx part of it.

**Comment by pkrawat1** [comment]
hi @ericel 

I use https://github.com/compodoc/compodoc for documentation.
you can install it and then run `compodoc -s` to start the server.

For users/auth issue,
* can you paste the console log.
* are the pins loaded, or they too are giving error. As in case of error in loading pins, login too would not work.
